# Example configuration file for forgejo-mcp
# This file demonstrates how to configure the application using viper
# Copy this file to config.yaml and update the values as needed
# You can place the config file in the root directory or ./config directory
#
# Migration Note: Configuration structure unchanged after SDK migration
# All existing configurations remain compatible with the official MCP SDK

# Server configuration (MCP server settings)
host: "localhost"
port: 3000

# Forgejo/Gitea configuration (API integration settings)
remote_url: "https://your-forgejo-instance.com"
auth_token: "your-auth-token-here"

# Client type configuration (optional, defaults to "auto")
# Options: "gitea", "forgejo", "auto"
# - "gitea": Use Gitea SDK for Gitea instances
# - "forgejo": Use Forgejo SDK for Forgejo instances
# - "auto": Automatically detect platform by querying /api/v1/version (recommended)
client_type: "auto"