# Forgejo MCP Configuration Example
#
# Copy this file to `config.yaml` in the current directory,
# or to `~/.forgejo-mcp/config.yaml` for user-wide configuration.

# URL of your Forgejo instance
# Required: Yes
# Environment variable: FORGEJO_MCP_FORGEJO_URL
forgejo_url: ""

# Authentication token for Forgejo API
# Required: Yes
# Environment variable: FORGEJO_MCP_AUTH_TOKEN
auth_token: "2a75296bb81c30c175177f3a1241c08544182df6"

# Enable debug logging
# Required: No (defaults to false)
# Environment variable: FORGEJO_MCP_DEBUG
debug: false

# Log level (debug, info, warn, error)
# Required: No (defaults to "info")
# Environment variable: FORGEJO_MCP_LOG_LEVEL
log_level: "info"
